New.

diff --git a/hooks/update b/hooks/update
--- a/hooks/update
+++ b/hooks/update
@@ -11,23 +11,30 @@ _prepare_locking
 
 exlock_now()        { _lock xn; }
 
-if ! [ "deploy" == "$1" ]; then
+if ! [ -z "$1" ] && ! [ "refs/heads/deploy" == "$1" ]; then
   exit 1
 fi
 
 exlock_now || exit 0
 
-unset GIT_DIR
-cd /home/git/www/blue.cse.buffalo.edu/
-git fetch --all > /dev/null
-git reset --hard origin/deploy > /dev/null
+NVM_DIR="/home/git/.nvm"
+[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
+export HOME="/home/git/"
+
+WORK_TREE=$HOME/www/blue.cse.buffalo.edu/
+if ! [ -z "$3" ]; then
+  git --work-tree=$WORK_TREE checkout $3
+fi
+cd $WORK_TREE
+
+echo "Building blue.cse.buffalo.edu..."
 if make ; then
-  rsync -ai build/* /mnt/ramdisk/blue.cse.buffalo.edu/build/ | while read unused filename; do
+  rsync -ai build/* /mnt/ramdisk/blue.cse.buffalo.edu/www/ | while read unused filename; do
     curl --request PURGE 'http://127.0.0.1/$filename' > /dev/null 2> /dev/null
     echo "Updated $filename"
   done
   echo "Success. Thanks for updating the website."
 else
-  echo "Build failed. Please try again."
+  echo "Failed. Please try again."
   exit 1
 fi
